.586P
.MODEL FLAT, stdcall

INCLUDE KERN.INC

includelib c:\masm32\lib\hal.lib

_TEXT SEGMENT 
;DWORD PTR [EBP+0CH];указывает на DRIVER_OBJECT
;DWORD PTR [EBP+08H];указывает на UNICODE_STRING
ENTRY PROC ;точка входа
PUSH EBP
	MOV EBP,ESP ;теперь EBP указывает на вершину стека
	PUSH EBX
	PUSH ESI
	PUSH EDI
MOV EDX,1200
	CLI
	MOV AL,10110110B            
	OUT 43H,AL
	IN  AL,61H
	OR  AL,3                    
	OUT 61H,AL
	MOV EAX,EDX
	OUT 42H,AL
	MOV AL,AH
	OUT 42H,AL
	MOV ECX,0FFFFFFH
	STI
LOO: 
	LOOP LOO
CLI
	IN  AL,61H
	AND AL,11111100B
	OUT 61H,AL
	STI
	MOV EAX,STATUS_DEVICE_CONFIGURATION_ERROR
	POP EDI
	POP ESI
	POP EBX
	POP EBP
	RET 8	
ENTRY ENDP
_TEXT ENDS
END ENTRY
